archives:
- format: binary
  name_template: '{{ .ProjectName }}-v{{ .Version }}-{{ .Os }}-{{ .Arch }}'
before:
  hooks:
  - go mod tidy
builds:
- env:
  - CGO_ENABLED=0
  flags:
  - -trimpath
  goarch:
  - amd64
  - "386"
  - arm
  - arm64
  goos:
  - freebsd
  - windows
  - linux
  - darwin
  ignore:
  - goarch: "386"
    goos: darwin
  - goarch: arm
    goos: windows
  ldflags:
  - -X main.Version={{ .Version }} -X main.Commit={{ .Commit }}
  mod_timestamp: '{{ .CommitTimestamp }}'
release:
  draft: false

